services:
  # 後端 Web Service
  - type: web
    name: csv-chart-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: backend
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: csv-chart-db
          property: connectionString
    autoDeploy: true

  # PostgreSQL 資料庫
  - type: pgsql
    name: csv-chart-db
    plan: free
    databaseName: csv_chart_system
    user: csv_chart_user 